CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30),
  age INT
);

CREATE TABLE books (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(30),
  user_id INT
);

ALTER TABLE books ADD FOREIGN KEY (user_id) REFERENCES users(id);